<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserSettingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create(
            'user_settings',
            function (Blueprint $table) {
                $table->unsignedInteger('userId');
                $table->string('signupIp', 45)->nullable();
                $table->integer('notificationOptions')->nullable();
                $table->integer('emailNotificationOptions')->nullable();
                $table->integer('pushNotificationOptions')->nullable();
                $table->tinyInteger('pushEnabled')->default(0);
                $table->string('appVersion', 50)->nullable();
                $table->string('emailKey', 64)->nullable();
                $table->dateTime('lastEmailedAt')->nullable();

                $table->primary('userId');

                $table->foreign(['userId'], 'user_settings_user')
                    ->references(['id'])
                    ->on('users')
                    ->onDelete('CASCADE')
                    ->onUpdate('CASCADE');

            }
        );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_settings');
    }
}
