<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateImagesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create(
            'images',
            function (Blueprint $table) {
                $table->increments('id');
                $table->unsignedInteger('userId')->nullable()->index();
                $table->string('directory', 100);
                $table->string('filename', 50);
                $table->integer('width')->nullable();
                $table->integer('height')->nullable();
                $table->integer('size')->nullable();
                $table->integer('optimizedSize')->nullable();
                $table->boolean('hasThumbnail')->default(false);
                $table->string('originalUrl', 255)->nullable();

                \Antriver\LaravelSiteUtils\Migrations\MigrationHelper::addTimestamps($table);

                $table->unique(['directory', 'filename'], 'directory_filename');

                $table->foreign(['userId'], 'image_user')
                    ->references(['id'])
                    ->on('users')
                    ->onDelete('SET NULL')
                    ->onUpdate('CASCADE');

            }
        );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('images');
    }
}
