<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create(
            'users',
            function (Blueprint $table) {
                $table->increments('id');
                $table->string('username', 50)->unique();
                $table->string('email', 191)->index();
                $table->string('password', 60);
                $table->boolean('admin')->default(false);
                $table->boolean('moderator')->default(false);
                $table->boolean('emailVerified')->default(false);
                $table->boolean('emailBounced')->default(false);
                $table->unsignedInteger('avatarImageId')->nullable();
                \Antriver\LaravelSiteUtils\Migrations\MigrationHelper::addTimestamps($table);
                \Antriver\LaravelSiteUtils\Migrations\MigrationHelper::addDeletedAt($table);
                $table->dateTime('deactivatedAt')->nullable();
            }
        );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
