<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateBansTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create(
            'bans',
            function (Blueprint $table) {
                $table->increments('id');
                $table->unsignedInteger('userId')->nullable();
                $table->string('ip', 45)->nullable()->default(null);
                $table->unsignedInteger('byUserId')->nullable();
                $table->unsignedInteger('unbannedByUserId')->nullable();
                $table->longText('reason');
                $table->longText('internalReason')->nullable();
                \Antriver\LaravelSiteUtils\Migrations\MigrationHelper::addTimestamps($table);
                \Antriver\LaravelSiteUtils\Migrations\MigrationHelper::addDeletedAt($table);
                $table->dateTime('expiresAt')->nullable();

                $table->index('userId', 'userId');
                $table->index('ip', 'ip');
                $table->index(['userId', 'updatedAt'], 'userId_deletedAt');
                $table->index(['ip', 'deletedAt'], 'ip_deletedAt');
                $table->index('expiresAt', 'expiresAt');
                $table->index('deletedAt', 'deletedAt');

                $table->foreign(['byUserId'], 'ban_by_user')
                    ->references(['id'])
                    ->on('users')
                    ->onDelete('SET NULL')
                    ->onUpdate('CASCADE');

                $table->foreign(['unbannedByUserId'], 'ban_unbanned_by_user')
                    ->references(['id'])
                    ->on('users')
                    ->onDelete('SET NULL')
                    ->onUpdate('CASCADE');

                $table->foreign(['userId'], 'ban_user')
                    ->references(['id'])
                    ->on('users')
                    ->onDelete('SET NULL')
                    ->onUpdate('CASCADE');

            }
        );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('bans');
    }
}
