<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserNameChangesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create(
            'user_name_changes',
            function (Blueprint $table) {
                $table->increments('id');
                $table->unsignedInteger('userId');
                $table->string('oldName', 50);
                $table->string('newName', 50);
                \Antriver\LaravelSiteUtils\Migrations\MigrationHelper::addCreatedAt($table);

                $table->index('oldName', 'oldname');
                $table->index('userId', 'userId');
                $table->index('newName', 'newname');

                $table->foreign('userId', 'user_name_change_user')
                    ->references('id')
                    ->on('users')
                    ->onDelete('CASCADE')
                    ->onUpdate('CASCADE');
            }
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_name_changes');
    }
}
