<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserSessionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create(
            'user_sessions',
            function (Blueprint $table) {
                $table->string('id', 64);
                $table->unsignedInteger('userId')->index();
                $table->string('ip', 45)->nullable()->index();
                $table->tinyInteger('adminLogin')->default(0);
                $table->dateTime('loggedInAt')->default(\DB::raw('CURRENT_TIMESTAMP'));
                $table->dateTime('loggedOutAt')->nullable();
                $table->dateTime('lastUsedAt')->nullable();

                $table->primary('id');

                $table->foreign(['userId'], 'user_sessions_user')
                    ->references(['id'])
                    ->on('users')
                    ->onDelete('CASCADE')
                    ->onUpdate('CASCADE');

            }
        );

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_sessions');
    }
}
