<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.5.0)
 *
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserEmailChangesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create(
            'user_email_changes',
            function (Blueprint $table) {
                $table->increments('id');
                $table->unsignedInteger('userId');
                $table->string('oldEmail', 200);
                $table->string('newEmail', 200);
                \Antriver\LaravelSiteUtils\Migrations\MigrationHelper::addCreatedAt($table);

                $table->index('userId', 'user_email_changes_user');

                $table->foreign('userId', 'user_email_change_user')
                    ->references('id')
                    ->on('users')
                    ->onDelete('CASCADE')
                    ->onUpdate('CASCADE');

            }
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_email_changes');
    }
}
